name "pihole"
maintainer "Giacomo Bagnoli"
maintainer_email "gbagnoli@gmail.com"
license "MIT"
description "Installs/Configures pihole quadlet"
version "0.1.0"

depends "datadog"
depends "podman"

issues_url "https://github.com/gbagnoli/devmachine/issues"
source_url "https://github.com/gbagnoli/devmachine"
chef_version ">=16"
supports "ubuntu", ">= 24.04"
supports "rocky", ">= 9.0"
