name "podman_nginx"
maintainer "Giacomo Bagnoli"
maintainer_email "gbagnoli@gmail.com"
license "MIT"
description "Installs/Configures podman based nginx"
version "0.1.0"

issues_url "https://github.com/gbagnoli/devmachine/issues"
source_url "https://github.com/gbagnoli/devmachine"
chef_version ">=17"
supports "rocky", ">= 9.0"
supports "ubuntu", ">= 22.04"
depends "logrotate"
