---
driver:
  name: vagrant
  provider: virtualbox
  cachier: true

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-22.04
    driver:
      box: ubuntu/jammy64

suites:
  - name: ubik
    run_list:
      - role[ubiktest]
    verifier:
      inspec_tests:
        - path: tests/integration/ubik/

  - name: marvin
    run_list:
      - role[marvintest]
    verifier:
      inspec_tests:
        - path: tests/integration/ubik/

  - name: bender
    run_list:
      - role[bendertest]
    verifier:
      inspec_tests:
        - path: tests/integration/ubik/
