Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Max: 80

Naming/HeredocDelimiterNaming:
  ForbiddenDelimiters:
    - END

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

inherit_from:
  - https://raw.githubusercontent.com/xinminlabs/rubocop-config-rufo/master/rubocop.yml
