source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef', '~> 16.0'
gem 'foodcritic'
gem 'inspec'
gem 'inspec-bin'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'rubocop'
gem 'rufo'
gem 'test-kitchen'
