[package]
name = "skillet_syncthing"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
skillet_datadog.workspace = true
skillet_core.workspace = true
skillet_podman.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
skillet_core = { workspace = true, features = ["test-utils"] }
