version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
jobs:
  style:
    docker:
      - image: 'cimg/ruby:3.1'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: bundle exec cookstyle site-cookbooks roles

  ubik_2204:
    machine:
      image: ubuntu-2204:202101-01
    steps:
      - checkout
      - ruby/install-deps

      - run:
          command: bundle exec inspec vendor tests/integration/ubik
          environment:
            BUNDLE_GEMFILE: .circleci/Gemfile

      - run:
          command: bundle exec kitchen test ubik-ubuntu-2204
          no_output_timeout: 1200
          environment:
            KITCHEN_YAML: .kitchen.ci.yml
            BUNDLE_GEMFILE: .circleci/Gemfile

  marvin_2204:
    machine:
      image: ubuntu-2204:202101-01
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: bundle exec inspec vendor tests/integration/ubik
          environment:
            BUNDLE_GEMFILE: .circleci/Gemfile

      - run:
          command: bundle exec kitchen test marvin-ubuntu-2204
          no_output_timeout: 1200
          environment:
            KITCHEN_YAML: .kitchen.ci.yml
            BUNDLE_GEMFILE: .circleci/Gemfile

  bender_2204:
    machine:
      image: ubuntu-2204:202101-01
    steps:
      - checkout

      - run:
          command: bundle exec inspec vendor tests/integration/ubik
          environment:
            BUNDLE_GEMFILE: .circleci/Gemfile

      - run:
          command: bundle exec kitchen test bender-ubuntu-2204
          no_output_timeout: 1200
          environment:
            KITCHEN_YAML: .kitchen.ci.yml
            BUNDLE_GEMFILE: .circleci/Gemfile

workflows:
  version: 2
  converge:
    jobs:
      - style
      # - ubik_2204:
      #     requires:
      #       - style
      # - marvin_2204:
      #     requires:
      #       - style
      # - bender_2204:
      #     requires:
      #       - style
