name 'dnscrypt_proxy'
maintainer 'Giacomo Bagnoli'
maintainer_email 'gbagnoli@gmail.com'
license 'mit'
description 'Installs and configure dnscrypt'
long_description 'Installs and configure dnscrypt'
version '0.1.0'
