name 'user'
maintainer 'Giacomo Bagnoli'
maintainer_email 'gbagnoli@gmail.com'
license 'mit'
description 'Installs/Configures user'
long_description 'Installs/Configures user'
version '0.1.0'

depends 'git'
depends 'gnome'
