[package]
name = "skillet_workstation"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
cloudflare.workspace = true
hex.workspace = true
keepass.workspace = true
keyutils.workspace = true
rpassword.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
skillet_caddy.workspace = true
skillet_hosts.workspace = true
tempfile.workspace = true
thiserror.workspace = true
