[package]
name = "skillet-smoke-fixture"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
skillet_core.workspace = true
skillet_podman.workspace = true
skillet_cli_common.workspace = true
thiserror.workspace = true
anyhow = "1.0"

[dev-dependencies]
skillet_core = { workspace = true, features = ["test-utils"] }
